### ISSUE TITLE
Deepstack error on face recognition

### ISSUE THREAD

**Issue by cooljackgi** [doitandbedone/ispyagentdvr-docker#345]
I get this error if i try to scan a face. 

can some one help me?
i get some recognions with the deepstack-ui docker, so i know it works.

```
Error: JSON Processor: JSON Processor: The operation was canceled.
Error: JSON Processor:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at CoreLogic.AI.FaceRecognizer.RegisterFace(String userid, Mat frame)
   at CoreLogic.Server.JsonProcessor.LoadJson(Int32 oid, Int32 ot, String lc, String command, String fullcmd, String data, RTCSession session)
Error: JSON Processor: JSON Processor: Unable to read data from the transport connection: Operation canceled.
Error: JSON Processor:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Error: JSON Processor: JSON Processor: Operation canceled
Error: JSON Processor: 
Operation canceled
```

**Comment by ispysoftware** [comment]
Have you started deepstack in face recognition mode? Have you checked the deepstack logs?  This error means there was no response from deepstack which could also be a firewall issue or a cpu overload issue.

**Comment by cooljackgi** [comment]
Sure, deepstack is started with face recogniton, 


here is the log from the docker with the deepstack:
`[GIN] 2021/11/07 - 07:06:44 | 200 | 19.054945254s |    192.168.3.20 | POST     /v1/vision/face/recognize
[GIN] 2021/11/07 - 07:07:36 | 200 |     378.517µs |    192.168.3.20 | POST     /v1/vision/face/list
[GIN] 2021/11/07 - 07:07:52 | 200 |     464.496µs |    192.168.3.20 | POST     /v1/vision/face/list
[GIN] 2021/11/07 - 07:07:55 | 200 |   7.68057533s |    192.168.3.20 | POST     /v1/vision/face/register
[GIN] 2021/11/07 - 07:12:29 | 200 |  9.159184769s |   192.168.3.200 | POST     /v1/vision/detection
[GIN] 2021/11/07 - 07:12:30 | 400 | 10.060467095s |   192.168.3.200 | POST     /v1/vision/face/recognize
[GIN] 2021/11/07 - 07:14:50 | 200 |  9.061257841s |   192.168.3.200 | POST     /v1/vision/detection
[GIN] 2021/11/07 - 07:14:51 | 400 |  9.968472526s |   192.168.3.200 | POST     /v1/vision/face/recognize
[GIN] 2021/11/07 - 07:16:03 | 200 | 10.366999025s |   192.168.3.200 | POST     /v1/vision/detection
[GIN] 2021/11/07 - 07:16:05 | 400 |  13.02748339s |   192.168.3.200 | POST     /v1/vision/face/recognize
[GIN] 2021/11/07 - 07:25:37 | 200 |     233.823µs |    192.168.3.20 | POST     /v1/vision/face/list
[GIN] 2021/11/07 - 07:25:46 | 200 |     216.053µs |    192.168.3.20 | POST     /v1/vision/face/list
[GIN] 2021/11/07 - 07:25:49 | 200 |  8.160926603s |    192.168.3.20 | POST     /v1/vision/face/register'

with the dvr agent on windows the deepstack works. 

on with port does the docker waits for the data from deepstack? mine is in 5000 like the Standard.

**Comment by cooljackgi** [comment]
I am a bit confused.

Now after a nice restart from all, i get this on the deepstack side:
'[GIN] 2021/11/07 - 08:54:46 | 200 |  9.931778818s |   192.168.3.200 | POST     /v1/vision/face/recognize
[GIN] 2021/11/07 - 08:54:55 | 200 |   8.35423536s |   192.168.3.200 | POST     /v1/vision/face/recognize
[GIN] 2021/11/07 - 08:55:03 | 200 |  6.885271935s |   192.168.3.200 | POST     /v1/vision/face/recognize
[GIN] 2021/11/07 - 08:55:13 | 200 |  6.615911092s |   192.168.3.200 | POST     /v1/vision/face/recognize
[GIN] 2021/11/07 - 08:55:26 | 200 |  9.304417697s |   192.168.3.200 | POST     /v1/vision/face/recognize
[GIN] 2021/11/07 - 08:55:37 | 200 |  9.946877451s |   192.168.3.200 | POST     /v1/vision/face/recognize
[GIN] 2021/11/07 - 08:55:46 | 200 |  8.748024198s |   192.168.3.200 | POST     /v1/vision/face/recognize
[GIN] 2021/11/07 - 08:55:57 | 200 | 10.059343229s |   192.168.3.200 | POST     /v1/vision/face/recognize
[GIN] 2021/11/07 - 08:56:04 | 400 |  6.596757757s |   192.168.3.200 | POST     /v1/vision/face/recognize
[GIN] 2021/11/07 - 08:56:13 | 400 |  6.186146552s |   192.168.3.200 | POST     /v1/vision/face/recognize'

but on the dvr side:
'Error: Detect Plates: Detect Plates: The operation was canceled.
Error: Detect Plates:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at CoreLogic.AI.FaceRecognizer.Detect()
Error: Detect Plates: Detect Plates: Unable to read data from the transport connection: Operation canceled.
Error: Detect Plates:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Error: Detect Plates: Detect Plates: Operation canceled
Error: Detect Plates: 
Operation canceled
detected: Camera 3 message: Detected
Processing TFACE (2,3)
detected: Camera 3 message: Detected
Processing TFACE (2,3)
Error: Detect Plates: Detect Plates: The operation was canceled.
Error: Detect Plates:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at CoreLogic.AI.FaceRecognizer.Detect()
Error: Detect Plates: Detect Plates: Unable to read data from the transport connection: Operation canceled.
Error: Detect Plates:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Error: Detect Plates: Detect Plates: Operation canceled
Error: Detect Plates: 
Operation canceled
detected: Camera 3 message: Detected
Processing TFACE (2,3)
detected: Camera 3 message: Detected
Processing TFACE (2,3)'

I did everything to turn off the plate service...

**Comment by cooljackgi** [comment]
I think i am getting closer (;

`detected: Camera 2 message: Detected
Processing TFACE (2,2)
detected: Camera 2 message: Detected
Processing TFACE (2,2)
detected: Camera 2 message: Detected
Processing TFACE (2,2)
detected: Camera 2 message: Detected
Processing TFACE (2,2)
detectedstopped: Camera 2
Processing STOPR (2,2)`

**Comment by ispysoftware** [comment]
ah some of the code that does plate recognition and facial recognition share some base classes that's currently logging errors as "Detect Plates" from both sources - will get that fixed up.
