### ISSUE TITLE
OpenDrive Issue: OpenDrive: Cannot perform runtime binding on a null reference

### ISSUE THREAD

**Issue by alexbn71** [doitandbedone/ispyagentdvr-docker#594]
Hi, I've setup OpenDrive on my AgentDVR (docker on Linux). The strange thing is that it works on the first cam I've setup to send photos... but on other cams I get this error:

`<html>
<body>

07:21:38 | OpenDrive: OpenDrive: Cannot perform runtime binding on a null reference
-- | --
07:21:38 | Error: OpenDrive: OpenDrive: Cannot perform runtime binding on a null reference
07:21:38 | OpenDrive: at CallSite.Target(Closure , CallSite , Object ) at CoreLogic.Cloud.OpenDrive.CreateFolder(String folderName, String parentID) at CoreLogic.Cloud.OpenDrive.GetFolderID(String path) at CoreLogic.Cloud.OpenDrive.Upload(UploadEntry ue)
07:21:38 | Error: OpenDrive: at CallSite.Target(Closure , CallSite , Object ) at CoreLogic.Cloud.OpenDrive.CreateFolder(String folderName, String parentID) at CoreLogic.Cloud.OpenDrive.GetFolderID(String path) at CoreLogic.Cloud.OpenDrive.Upload(UploadEntry ue)
07:21:38 | Cannot perform runtime binding on a null reference

</body>
</html>`

I've tried to disable this setup on all cams and leave another cam with this activated... and it does't work. It work only on the same cam I used the first time. I already tried restarting agentdvr.

**Comment by ispysoftware** [comment]
what settings do you have for the cloud provider?

**Comment by alexbn71** [comment]
![image](https://user-images.githubusercontent.com/20998190/229033342-909c2c6f-708a-45b2-80ee-f965f5c62c66.png)
![image](https://user-images.githubusercontent.com/20998190/229033408-7b986c49-6661-46e6-9191-cafad0b130c1.png)

**Comment by ispysoftware** [comment]
I think it might be something to do with opendrive having the worst API i've ever seen. Will take a look

**Comment by ispysoftware** [comment]
fix in next update

**Comment by alexbn71** [comment]
Thank you Sean
