### ISSUE TITLE
AgentDVR wont start and keeps trying to install ffmpeg6

### ISSUE THREAD

**Issue by Evankkm** [doitandbedone/ispyagentdvr-docker#692]
Here is the log
Unhandled exception. System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& )
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle , Boolean& )
   at Interop.Kernel32.SetEvent(SafeWaitHandle )
   at System.Threading.EventWaitHandle.Set()
   at CoreLogic.Setup.<>c__DisplayClass2_0.<SetPermissions>b__2(Object sender, EventArgs e)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.CompletionCallback(Object , Boolean )
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context(Object , Boolean )
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context_f(Object )
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext , ContextCallback , Object )
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext , ContextCallback , Object )
   at System.Threading.ExecutionContext.Run(ExecutionContext , ContextCallback , Object )
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(_ThreadPoolWaitOrTimerCallback , Boolean )
   at System.Threading.RegisteredWaitHandle.PerformCallback(Boolean )
   at System.Threading.PortableThreadPool.CompleteWait(RegisteredWaitHandle , Boolean )
   at System.Threading.CompleteWaitThreadPoolWorkItem.CompleteWait()
   at System.Threading.CompleteWaitThreadPoolWorkItem.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by ispysoftware** [comment]
Is that everything in the log?
This shouldn't cause startup to fail - you might just need to wait for ffmpeg to finish installing
Are you using the docker version?

**Comment by Evankkm** [comment]
Yes I’m using the docker version, I’m using the agentdvr for more than 2 months and I had no problems until the latest update. Since then the agentdvr starts and keeps trying to instatall ffmpeg6Sent from my iPhoneOn 22 Mar 2024, at 2:38 AM, sean t ***@***.***> wrote:﻿
Is that everything in the log?
This shouldn't cause startup to fail - you might just need to wait for ffmpeg to finish installing
Are you using the docker version?

**Comment by ispysoftware** [comment]
how did you update it?

**Comment by Evankkm** [comment]
Sometimes I get this message too Sent from my iPhoneOn 22 Mar 2024, at 10:01 AM, Evan K ***@***.***> wrote:﻿Yes I’m using the docker version, I’m using the agentdvr for more than 2 months and I had no problems until the latest update. Since then the agentdvr starts and keeps trying to instatall ffmpeg6Sent from my iPhoneOn 22 Mar 2024, at 2:38 AM, sean t ***@***.***> wrote:﻿
Is that everything in the log?
This shouldn't cause startup to fail - you might just need to wait for ffmpeg to finish installing
Are you using the docker version?

**Comment by ispysoftware** [comment]
the docker version should have ffmpeg packaged with it - you'll need to check the rest of the logs

**Comment by Evankkm** [comment]
That’s everything I get in the log On 22 Mar 2024, at 10:28 AM, sean t ***@***.***> wrote:﻿
the docker version should have ffmpeg packaged with it - you'll need to check the rest of the logs

**Comment by ispysoftware** [comment]
maybe try 
https://github.com/MekayelAnik/ispyagentdvr-docker

**Comment by Evankkm** [comment]
Thanks, I'll check it out.

**Comment by fuentes81081** [comment]
Seems like ffmpeg6 is not download/extracting properly.  Here's how I got around it:

Get into the container's cli, mine's called ispyagentdvr
`$ docker exec -it ispyagentdvr bash`

Install wget 
`# apt install wget`

Download the ffmpeg6 file into the agent directory
`# cd agent; wget https://ispyrtcdata.blob.core.windows.net/downloads/ffmpeg6-linuxx64.tar.xz`

Extract into the ffmpeg6 directory
`# tar -xvf ffmpeg6-linuxx64.tar.xz --strip-components=1 -C "ffmpeg6"`

Restart the container and you should be done.
Nothing against MekayelAnik/ispyagentdvr-docker, but I can't get AV_HWDEVICE_TYPE_CUDA working on that one.

**Comment by ispysoftware** [comment]
Looks like the docker file includes an old version of ffmpeg - i'll get it updated

**Comment by electricmessiah** [comment]
This is still happening. UI gets stuck, but my container has "ffmpeg is already the newest version (7:7.0.2-3)."

**Comment by ispysoftware** [comment]
Agent is built against a specific version of ffmpeg - v6 in shared mode. It's not going to work with v7
